const data = {
            lessons: [
                {
                    lesson: 1,
                    title: "歡迎你來臺灣! (Chào mừng bạn đến Đài Loan!)",
                    vocab: [
                        { "char": "你", "pinyin": "nǐ", "meaning": "bạn, anh, chị, em" },
                        { "char": "來", "pinyin": "lái", "meaning": "đến" },
                        { "char": "是", "pinyin": "shì", "meaning": "là, phải" },
                        { "char": "小姐", "pinyin": "xiǎojiě", "meaning": "cô, tiểu thư" },
                        { "char": "嗎", "pinyin": "ma", "meaning": "không? (trợ từ)" },
                        { "char": "接", "pinyin": "jiē", "meaning": "đón" },
                        { "char": "我們", "pinyin": "wǒmen", "meaning": "chúng tôi" },
                        { "char": "我", "pinyin": "wǒ", "meaning": "tôi" },
                        { "char": "這", "pinyin": "zhè", "meaning": "đây, này" },
                        { "char": "先生", "pinyin": "xiānshēng", "meaning": "ông, ngài" },
                        { "char": "好", "pinyin": "hǎo", "meaning": "tốt, khỏe" },
                        { "char": "姓", "pinyin": "xìng", "meaning": "họ là" },
                        { "char": "叫", "pinyin": "jiào", "meaning": "gọi là, tên là" },
                        { "char": "你們", "pinyin": "nǐmen", "meaning": "các bạn" },
                        { "char": "歡迎", "pinyin": "huānyíng", "meaning": "chào mừng" },
                        { "char": "請問", "pinyin": "qǐngwèn", "meaning": "xin hỏi" },
                        { "char": "謝謝", "pinyin": "xièxie", "meaning": "cảm ơn" },
                        { "char": "不客氣", "pinyin": "búkèqi", "meaning": "không có gì" },
                        { "char": "請", "pinyin": "qǐng", "meaning": "mời, xin" },
                        { "char": "喝", "pinyin": "hē", "meaning": "uống" },
                        { "char": "茶", "pinyin": "chá", "meaning": "trà" },
                        { "char": "很", "pinyin": "hěn", "meaning": "rất" },
                        { "char": "好喝", "pinyin": "hǎohē", "meaning": "ngon (đồ uống)" },
                        { "char": "什麼", "pinyin": "shénme", "meaning": "cái gì" },
                        { "char": "人", "pinyin": "rén", "meaning": "người" },
                        { "char": "喜歡", "pinyin": "xǐhuān", "meaning": "thích" },
                        { "char": "呢", "pinyin": "ne", "meaning": "còn... thì sao?" },
                        { "char": "他", "pinyin": "tā", "meaning": "anh ấy" },
                        { "char": "不", "pinyin": "bù", "meaning": "không" },
                        { "char": "哪", "pinyin": "nǎ", "meaning": "nào" },
                        { "char": "要", "pinyin": "yào", "meaning": "muốn" },
                        { "char": "咖啡", "pinyin": "kāfēi", "meaning": "cà phê" },
                        { "char": "對不起", "pinyin": "duìbùqǐ", "meaning": "xin lỗi" },
                    ],
                    grammar: [
                        { title: "Cách đặt câu hỏi", content: "<b>Câu hỏi Chính-Phản (A-not-A):</b> V + 不 + V? <br><i>Ví dụ: 你是不是日本人？(Bạn có phải là người Nhật không?)</i><br><br><b>Câu hỏi với 嗎 (ma):</b> Câu trần thuật + 嗎? <br><i>Ví dụ: 你是陳月美小姐嗎？(Bạn có phải là cô Trần Nguyệt Mỹ không?)</i>" },
                        { title: "Phó từ chỉ mức độ 很 (hěn)", content: "Thường đứng trước tính từ. Trong câu trần thuật đơn giản, nó giúp câu tự nhiên hơn và không nhất thiết mang nghĩa 'rất'.<br><i>Ví dụ: 我很好。(Tôi khỏe.)</i>" },
                        { title: "Câu hỏi với 呢 (ne)", content: "Dùng để hỏi lại một câu hỏi tương tự về một đối tượng khác.<br><i>Ví dụ: 我是美國人，你呢？(Tôi là người Mỹ, còn bạn thì sao?)</i>" }
                    ]
                },
                {
                    lesson: 2,
                    title: "我的家人 (Gia đình của tôi)",
                    vocab: [
                        { char: '的', pinyin: 'de', meaning: 'của' },
                        { char: '家人', pinyin: 'jiārén', meaning: 'người nhà' },
                        { char: '家', pinyin: 'jiā', meaning: 'nhà' },
                        { char: '漂亮', pinyin: 'piàoliang', meaning: 'xinh đẹp' },
                        { char: '房子', pinyin: 'fángzi', meaning: 'ngôi nhà' },
                        { char: '坐', pinyin: 'zuò', meaning: 'ngồi' },
                        { char: '有', pinyin: 'yǒu', meaning: 'có' },
                        { char: '多', pinyin: 'duō', meaning: 'nhiều' },
                        { char: '照片', pinyin: 'zhàopiàn', meaning: 'ảnh' },
                        { char: '都', pinyin: 'dōu', meaning: 'đều' },
                        { char: '照相', pinyin: 'zhàoxiàng', meaning: 'chụp ảnh' },
                        { char: '張', pinyin: 'zhāng', meaning: 'tấm, bức (lượng từ)' },
                        { char: '好看', pinyin: 'hǎokàn', meaning: 'đẹp, ưa nhìn' },
                        { char: '誰', pinyin: 'shéi', meaning: 'ai' },
                        { char: '姐姐', pinyin: 'jiějie', meaning: 'chị gái' },
                        { char: '妹妹', pinyin: 'mèimei', meaning: 'em gái' },
                        { char: '爸爸', pinyin: 'bàba', meaning: 'bố' },
                        { char: '媽媽', pinyin: 'māma', meaning: 'mẹ' },
                        { char: '伯母', pinyin: 'bómǔ', meaning: 'bác gái' },
                        { char: '您', pinyin: 'nín', meaning: 'ngài, ông, bà' },
                        { char: '名字', pinyin: 'míngzi', meaning: 'tên' },
                        { char: '書', pinyin: 'shū', meaning: 'sách' },
                        { char: '哥哥', pinyin: 'gēge', meaning: 'anh trai' },
                        { char: '老師', pinyin: 'lǎoshī', meaning: 'giáo viên' },
                        { char: '看書', pinyin: 'kànshū', meaning: 'đọc sách' },
                        { char: '幾', pinyin: 'jǐ', meaning: 'mấy' },
                        { char: '個', pinyin: 'ge', meaning: 'cái, con (lượng từ)' },
                        { char: '沒', pinyin: 'méi', meaning: 'không có' },
                        { char: '兄弟', pinyin: 'xiōngdì', meaning: 'anh em trai' },
                        { char: '姐妹', pinyin: 'jiěmèi', meaning: 'chị em gái' },
                        { char: '兩', pinyin: 'liǎng', meaning: 'hai' },
                    ],
                    grammar: [
                        { title: 'Sở hữu cách với 的 (de)', content: 'Chỉ sự sở hữu. <i>Ví dụ: 我的書 (sách của tôi).</i> Có thể lược bỏ khi quan hệ thân thiết.' },
                        { title: 'Câu tồn tại với 有 (yǒu)', content: 'Diễn tả sự tồn tại. <i>Ví dụ: 你家有很多照片。(Nhà bạn có nhiều ảnh).</i>' },
                        { title: 'Phó từ 都 (dōu)', content: 'Nghĩa là "đều". <i>Ví dụ: 我們都姓陳。(Chúng tôi đều họ Trần).</i>' },
                        { title: 'Lượng từ 個 (ge) và 張 (zhāng)', content: 'Bắt buộc khi có số từ. <i>Ví dụ: 一個哥哥, 兩張照片.</i>' },
                    ]
                },
                {
                    lesson: 3,
                    title: "週末做什麼? (Cuối tuần làm gì?)",
                    vocab: [
                        { char: '週末', pinyin: 'zhōumò', meaning: 'cuối tuần' },
                        { char: '聽', pinyin: 'tīng', meaning: 'nghe' },
                        { char: '音樂', pinyin: 'yīnyuè', meaning: 'âm nhạc' },
                        { char: '運動', pinyin: 'yùndòng', meaning: 'vận động' },
                        { char: '打', pinyin: 'dǎ', meaning: 'đánh (bóng)' },
                        { char: '網球', pinyin: 'wǎngqiú', meaning: 'quần vợt' },
                        { char: '和', pinyin: 'hàn', meaning: 'và' },
                        { char: '游泳', pinyin: 'yóuyǒng', meaning: 'bơi lội' },
                        { char: '常', pinyin: 'cháng', meaning: 'thường xuyên' },
                        { char: '也', pinyin: 'yě', meaning: 'cũng' },
                        { char: '踢', pinyin: 'tī', meaning: 'đá (bóng)' },
                        { char: '足球', pinyin: 'zúqiú', meaning: 'bóng đá' },
                        { char: '覺得', pinyin: 'juéde', meaning: 'cảm thấy' },
                        { char: '好玩', pinyin: 'hǎowán', meaning: 'vui' },
                        { char: '明天', pinyin: 'míngtiān', meaning: 'ngày mai' },
                        { char: '早上', pinyin: 'zǎoshang', meaning: 'buổi sáng' },
                        { char: '去', pinyin: 'qù', meaning: 'đi' },
                        { char: '怎麼樣', pinyin: 'zěnmeyàng', meaning: 'thế nào?' },
                        { char: '看', pinyin: 'kàn', meaning: 'xem' },
                        { char: '電影', pinyin: 'diànyǐng', meaning: 'phim' },
                        { char: '想', pinyin: 'xiǎng', meaning: 'muốn, nghĩ' },
                        { char: '還是', pinyin: 'háishì', meaning: 'hay là' },
                        { char: '吧', pinyin: 'ba', meaning: 'nhé, đi' },
                        { char: '可以', pinyin: 'kěyǐ', meaning: 'có thể' },
                        { char: '學', pinyin: 'xué', meaning: 'học' },
                        { char: '中文', pinyin: 'Zhōngwén', meaning: 'tiếng Trung' },
                        { char: '一起', pinyin: 'yìqǐ', meaning: 'cùng nhau' },
                        { char: '吃', pinyin: 'chī', meaning: 'ăn' },
                        { char: '晚飯', pinyin: 'wǎnfàn', meaning: 'cơm tối' },
                        { char: '菜', pinyin: 'cài', meaning: 'món ăn' },
                    ],
                    grammar: [
                        { title: 'Vị trí của từ chỉ thời gian', content: 'Thường đứng trước hoặc sau chủ ngữ. <i>Ví dụ: 明天我們去看電影。</i>' },
                        { title: 'Cấu trúc 去 + Động từ', content: 'Diễn tả ý định. <i>Ví dụ: 我們去踢足球。</i>' },
                        { title: 'Câu chủ đề', content: 'Đưa chủ đề lên đầu câu. <i>Ví dụ: 美國電影、臺灣電影，我都想看。</i>' },
                        { title: 'Thứ tự phó từ 也, 都, 常', content: 'Thứ tự: 也 > 都 / 常. <i>Ví dụ: 我常打籃球，也常踢足球。</i>' },
                        { title: 'Gợi ý với 吧 (ba)', content: 'Đặt cuối câu để gợi ý. <i>Ví dụ: 我們看臺灣電影吧！</i>' },
                    ]
                },
                {
                    lesson: 4,
                    title: '請問一共多少錢? (Xin hỏi tổng cộng bao nhiêu tiền?)',
                    vocab: [
                        { char: '一共', pinyin: 'yígòng', meaning: 'tổng cộng' },
                        { char: '多少', pinyin: 'duōshǎo', meaning: 'bao nhiêu' },
                        { char: '錢', pinyin: 'qián', meaning: 'tiền' },
                        { char: '老闆', pinyin: 'lǎobǎn', meaning: 'ông chủ' },
                        { char: '買', pinyin: 'mǎi', meaning: 'mua' },
                        { char: '杯', pinyin: 'bēi', meaning: 'cốc, ly' },
                        { char: '熱', pinyin: 'rè', meaning: 'nóng' },
                        { char: '包子', pinyin: 'bāozi', meaning: 'bánh bao' },
                        { char: '大/中/小', pinyin: 'dà/zhōng/xiǎo', meaning: 'to/vừa/nhỏ' },
                        { char: '幫', pinyin: 'bāng', meaning: 'giúp' },
                        { char: '微波', pinyin: 'wéibō', meaning: 'vi sóng' },
                        { char: '百', pinyin: 'bǎi', meaning: 'trăm' },
                        { char: '塊', pinyin: 'kuài', meaning: 'đồng (tiền)' },
                        { char: '支', pinyin: 'zhī', meaning: 'chiếc (lượng từ)' },
                        { char: '新', pinyin: 'xīn', meaning: 'mới' },
                        { char: '手機', pinyin: 'shǒujī', meaning: 'điện thoại di động' },
                        { char: '太', pinyin: 'tài', meaning: 'quá, lắm' },
                        { char: '舊', pinyin: 'jiù', meaning: 'cũ' },
                        { char: '了', pinyin: 'le', meaning: 'rồi (trợ từ)' },
                        { char: '種', pinyin: 'zhǒng', meaning: 'loại, kiểu' },
                        { char: '能', pinyin: 'néng', meaning: 'có thể' },
                        { char: '上網', pinyin: 'shàngwǎng', meaning: 'lên mạng' },
                        { char: '貴', pinyin: 'guì', meaning: 'đắt' },
                        { char: '賣', pinyin: 'mài', meaning: 'bán' },
                        { char: '便宜', pinyin: 'piányí', meaning: 'rẻ' },
                        { char: '萬', pinyin: 'wàn', meaning: 'vạn (10.000)' },
                        { char: '千', pinyin: 'qiān', meaning: 'nghìn' },
                    ],
                    grammar: [
                        { title: 'Lượng từ 塊, 杯, 支, 種', content: 'Các lượng từ phổ biến dùng để đếm đồ vật và tiền tệ.' },
                        { title: 'Giới từ 幫 (bāng)', content: 'Giúp ai làm gì. <i>Ví dụ: 請幫我微波。(Xin hãy vi sóng giúp tôi).</i>' },
                        { title: 'Cụm 的 (de) lược bỏ danh từ', content: 'Khi danh từ đã rõ, có thể lược bỏ. <i>Ví dụ: 我要新的。(Tôi muốn cái mới).</i>' },
                        { title: 'Cấu trúc 太...了 (tài...le)', content: '...quá rồi. <i>Ví dụ: 太貴了。(Đắt quá).</i>' },
                        { title: '多 (duō) sau số từ', content: 'Chỉ số lượng "...hơn". <i>Ví dụ: 一萬五千多。(Hơn 15.000).</i>' },
                    ]
                },
                {
                    lesson: 5,
                    title: '牛肉麵真好吃 (Mì bò thật ngon)',
                    vocab: [
                        { char: '牛肉', pinyin: 'niúròu', meaning: 'thịt bò' },
                        { char: '麵', pinyin: 'miàn', meaning: 'mì' },
                        { char: '真', pinyin: 'zhēn', meaning: 'thật là' },
                        { char: '好吃', pinyin: 'hǎochī', meaning: 'ngon (đồ ăn)' },
                        { char: '說', pinyin: 'shuō', meaning: 'nói' },
                        { char: '少', pinyin: 'shǎo', meaning: 'ít' },
                        { char: '有名', pinyin: 'yǒumíng', meaning: 'nổi tiếng' },
                        { char: '小吃', pinyin: 'xiǎochī', meaning: 'đồ ăn vặt' },
                        { char: '最', pinyin: 'zuì', meaning: 'nhất' },
                        { char: '湯', pinyin: 'tāng', meaning: 'canh, súp' },
                        { char: '這麼', pinyin: 'zhème', meaning: 'như vậy' },
                        { char: '知道', pinyin: 'zhīdào', meaning: 'biết' },
                        { char: '家', pinyin: 'jiā', meaning: 'quán (lượng từ)' },
                        { char: '店', pinyin: 'diàn', meaning: 'cửa hàng' },
                        { char: '一定', pinyin: 'yídìng', meaning: 'nhất định' },
                        { char: '點', pinyin: 'diǎn', meaning: 'gọi món' },
                        { char: '碗', pinyin: 'wǎn', meaning: 'bát, tô' },
                        { char: '餐廳', pinyin: 'cāntīng', meaning: 'nhà hàng' },
                        { char: '可是', pinyin: 'kěshì', meaning: 'nhưng' },
                        { char: '辣', pinyin: 'là', meaning: 'cay' },
                        { char: '怕', pinyin: 'pà', meaning: 'sợ' },
                        { char: '所以', pinyin: 'suǒyǐ', meaning: 'cho nên' },
                        { char: '自己', pinyin: 'zìjǐ', meaning: 'tự mình' },
                        { char: '做飯', pinyin: 'zuòfàn', meaning: 'nấu cơm' },
                        { char: '得', pinyin: 'de', meaning: '(bổ ngữ)' },
                        { char: '會', pinyin: 'huì', meaning: 'biết (kỹ năng)' },
                        { char: '甜點', pinyin: 'tiándiǎn', meaning: 'tráng miệng' },
                        { char: '不錯', pinyin: 'búcuò', meaning: 'không tệ' },
                        { char: '教', pinyin: 'jiāo', meaning: 'dạy' },
                        { char: '到', pinyin: 'dào', meaning: 'đến' },
                    ],
                    grammar: [
                        { title: '有一點 (yǒu yìdiǎn)', content: 'Hơi, một chút. <i>Ví dụ: 有一點辣。(Hơi cay).</i>' },
                        { title: 'Bổ ngữ trình độ 得 (de)', content: 'V + 得 + Adj. <i>Ví dụ: 你做飯做得怎麼樣？(Bạn nấu ăn thế nào?).</i>' },
                        { title: 'Động từ năng nguyện 會 (huì)', content: 'Biểu thị kỹ năng học được. <i>Ví dụ: 你會做飯嗎？</i>' },
                        { title: 'Giới từ 到 (dào)', content: 'Đến (đích đến). <i>Ví dụ: 你到我家來。(Bạn đến nhà tôi chơi).</i>' },
                    ]
                },
                {
                    lesson: 6,
                    title: '他們學校在山上 (Trường họ ở trên núi)',
                    vocab: [
                        { char: '他們', pinyin: 'tāmen', meaning: 'họ, bọn họ' },
                        { char: '學校', pinyin: 'xuéxiào', meaning: 'trường học' },
                        { char: '在', pinyin: 'zài', meaning: 'ở, tại' },
                        { char: '山上', pinyin: 'shānshàng', meaning: 'trên núi' },
                        { char: '哪裡', pinyin: 'nǎlǐ', meaning: 'ở đâu' },
                        { char: '遠', pinyin: 'yuǎn', meaning: 'xa' },
                        { char: '那裡', pinyin: 'nàlǐ', meaning: 'ở đó' },
                        { char: '風景', pinyin: 'fēngjǐng', meaning: 'phong cảnh' },
                        { char: '美', pinyin: 'měi', meaning: 'đẹp' },
                        { char: '前面/後面', pinyin: 'qiánmiàn/hòumiàn', meaning: 'phía trước/phía sau' },
                        { char: '海', pinyin: 'hǎi', meaning: 'biển' },
                        { char: '山', pinyin: 'shān', meaning: 'núi' },
                        { char: '地方', pinyin: 'dìfang', meaning: 'nơi, chỗ' },
                        { char: '現在', pinyin: 'xiànzài', meaning: 'bây giờ' },
                        { char: '附近', pinyin: 'fùjìn', meaning: 'gần đây' },
                        { char: '樓下', pinyin: 'lóuxià', meaning: 'dưới lầu' },
                        { char: '找', pinyin: 'zhǎo', meaning: 'tìm' },
                        { char: '朋友', pinyin: 'péngyou', meaning: 'bạn bè' },
                        { char: '上課', pinyin: 'shàngkè', meaning: 'vào lớp' },
                        { char: '近', pinyin: 'jìn', meaning: 'gần' },
                        { char: '方便', pinyin: 'fāngbiàn', meaning: 'thuận tiện' },
                        { char: '學生', pinyin: 'xuéshēng', meaning: 'học sinh' },
                        { char: '東西', pinyin: 'dōngxi', meaning: 'đồ đạc' },
                        { char: '外面/裡面', pinyin: 'wàimiàn/lǐmiàn', meaning: 'bên ngoài/bên trong' },
                        { char: '商店', pinyin: 'shāngdiàn', meaning: 'cửa hàng' },
                        { char: '宿舍', pinyin: 'sùshè', meaning: 'ký túc xá' },
                        { char: '樓', pinyin: 'lóu', meaning: 'tầng, lầu' },
                        { char: '圖書館', pinyin: 'túshūguǎn', meaning: 'thư viện' },
                        { char: '旁邊', pinyin: 'pángbiān', meaning: 'bên cạnh' },
                        { char: '教室', pinyin: 'jiàoshì', meaning: 'phòng học' },
                        { char: '游泳池', pinyin: 'yóuyǒngchí', meaning: 'bể bơi' },
                    ],
                    grammar: [
                        { title: 'Từ chỉ vị trí 在 (zài)', content: 'Biểu thị vị trí. <i>Ví dụ: 他們學校在山上。</i>' },
                        { title: 'Câu tồn tại với 有 (yǒu)', content: 'Nơi chốn + 有 + Người/Vật. <i>Ví dụ: 山上有兩家咖啡店。</i>' },
                        { title: 'Lặp lại động từ (V一V)', content: 'Làm hành động nhẹ nhàng hơn. <i>Ví dụ: 我想去看看。</i>' },
                        { title: 'Phủ định với 不是 (bú shì)', content: '"Không phải là...". <i>Ví dụ: 這裏不是很近。</i>' },
                    ]
                },
                {
                    lesson: 7,
                    title: '早上九點去KTV (9 giờ sáng đi KTV)',
                    vocab: [
                        { char: '點', pinyin: 'diǎn', meaning: 'giờ' },
                        { char: '唱歌', pinyin: 'chànggē', meaning: 'hát' },
                        { char: '分', pinyin: 'fēn', meaning: 'phút' },
                        { char: '見面', pinyin: 'jiànmiàn', meaning: 'gặp mặt' },
                        { char: '從', pinyin: 'cóng', meaning: 'từ' },
                        { char: '中午', pinyin: 'zhōngwǔ', meaning: 'buổi trưa' },
                        { char: '得', pinyin: 'děi', meaning: 'phải' },
                        { char: '銀行', pinyin: 'yínháng', meaning: 'ngân hàng' },
                        { char: '時候', pinyin: 'shíhou', meaning: 'lúc, khi' },
                        { char: '後天', pinyin: 'hòutiān', meaning: 'ngày kia' },
                        { char: '有空', pinyin: 'yǒukōng', meaning: 'có thời gian rảnh' },
                        { char: '再見', pinyin: 'zàijiàn', meaning: 'tạm biệt' },
                        { char: '午餐', pinyin: 'wǔcān', meaning: 'bữa trưa' },
                        { char: '剛', pinyin: 'gāng', meaning: 'vừa mới' },
                        { char: '下課', pinyin: 'xiàkè', meaning: 'tan học' },
                        { char: '下午', pinyin: 'xiàwǔ', meaning: 'buổi chiều' },
                        { char: '半', pinyin: 'bàn', meaning: 'rưỡi, nửa' },
                        { char: '比賽', pinyin: 'bǐsài', meaning: 'trận đấu' },
                        { char: '結束', pinyin: 'jiéshù', meaning: 'kết thúc' },
                        { char: '最近', pinyin: 'zuìjìn', meaning: 'gần đây' },
                        { char: '忙', pinyin: 'máng', meaning: 'bận' },
                        { char: '每', pinyin: 'měi', meaning: 'mỗi' },
                        { char: '天', pinyin: 'tiān', meaning: 'ngày' },
                        { char: '書法', pinyin: 'shūfǎ', meaning: 'thư pháp' },
                        { char: '課', pinyin: 'kè', meaning: 'tiết học' },
                        { char: '開始', pinyin: 'kāishǐ', meaning: 'bắt đầu' },
                        { char: '字', pinyin: 'zì', meaning: 'chữ' },
                        { char: '寫', pinyin: 'xiě', meaning: 'viết' },
                        { char: '問', pinyin: 'wèn', meaning: 'hỏi' },
                    ],
                    grammar: [
                        { title: 'Cấu trúc 從...到... (cóng...dào...)', content: 'Từ...đến... <i>Ví dụ: 從早上七點到中午十二點。</i>' },
                        { title: 'Hành động tiếp diễn với 在 (zài)', content: 'Đang làm gì. <i>Ví dụ: 你在吃飯啊？</i>' },
                        { title: 'Mỗi... với 每 (měi)', content: 'Thường đi với 都. <i>Ví dụ: 每天晚上都上書法課。</i>' },
                        { title: 'Xin phép với 可以 (kěyǐ)', content: 'Có thể...không? <i>Ví dụ: 我可以去看看嗎？</i>' },
                    ]
                },
                {
                    lesson: 8,
                    title: '坐火車去臺南 (Đi tàu hỏa đến Đài Nam)',
                    vocab: [
                        { char: '坐', pinyin: 'zuò', meaning: 'ngồi, đi (phương tiện)' },
                        { char: '火車', pinyin: 'huǒchē', meaning: 'tàu hỏa' },
                        { char: '跟', pinyin: 'gēn', meaning: 'với, cùng' },
                        { char: '玩', pinyin: 'wán', meaning: 'chơi' },
                        { char: '怎麼', pinyin: 'zěnme', meaning: 'làm sao' },
                        { char: '慢', pinyin: 'màn', meaning: 'chậm' },
                        { char: '鐘頭', pinyin: 'zhōngtóu', meaning: 'tiếng đồng hồ' },
                        { char: '比較', pinyin: 'bǐjiào', meaning: 'tương đối, hơn' },
                        { char: '快', pinyin: 'kuài', meaning: 'nhanh' },
                        { char: '車票', pinyin: 'chēpiào', meaning: 'vé xe' },
                        { char: '非常', pinyin: 'fēicháng', meaning: 'vô cùng' },
                        { char: '但是', pinyin: 'dànshì', meaning: 'nhưng' },
                        { char: '又', pinyin: 'yòu', meaning: 'vừa...vừa...' },
                        { char: '舒服', pinyin: 'shūfu', meaning: 'thoải mái' },
                        { char: '站', pinyin: 'zhàn', meaning: 'trạm, bến' },
                        { char: '或是', pinyin: 'huòshì', meaning: 'hoặc là' },
                        { char: '同學', pinyin: 'tóngxué', meaning: 'bạn học' },
                        { char: '參觀', pinyin: 'cānguān', meaning: 'tham quan' },
                        { char: '古代', pinyin: 'gǔdài', meaning: 'cổ đại' },
                        { char: '騎', pinyin: 'qí', meaning: 'cưỡi, đi (xe)' },
                        { char: '機車', pinyin: 'jīchē', meaning: 'xe máy' },
                        { char: '載', pinyin: 'zài', meaning: 'chở' },
                        { char: '捷運', pinyin: 'jiéyùn', meaning: 'tàu điện ngầm' },
                        { char: '比', pinyin: 'bǐ', meaning: 'hơn (so sánh)' },
                        { char: '計程車', pinyin: 'jìchéngchē', meaning: 'taxi' },
                    ],
                    grammar: [
                        { title: 'Cùng làm gì với 跟 (gēn)', content: '<i>Ví dụ: 我想跟朋友去臺南玩。</i>' },
                        { title: 'Hỏi cách thức với 怎麼 (zěnme)', content: '<i>Ví dụ: 怎麼去？</i>' },
                        { title: 'So sánh ngầm với 比較 (bǐjiào)', content: '...hơn. <i>Ví dụ: 坐高鐵比較快。</i>' },
                        { title: '又...又... (yòu...yòu...)', content: 'Vừa...vừa... <i>Ví dụ: 又快又舒服。</i>' },
                        { title: 'So sánh với 比 (bǐ)', content: 'A + 比 + B + Adj. <i>Ví dụ: 騎機車比坐公車快嗎？</i>' },
                    ]
                },
                {
                    lesson: 9,
                    title: '放假去哪裡玩? (Nghỉ lễ đi đâu chơi?)',
                    vocab: [
                        { char: '星期', pinyin: 'xīngqī', meaning: 'tuần' },
                        { char: '回國', pinyin: 'huíguó', meaning: 'về nước' },
                        { char: '打算', pinyin: 'dǎsuàn', meaning: 'dự định' },
                        { char: '電視', pinyin: 'diànshì', meaning: 'TV' },
                        { char: '影片', pinyin: 'yǐngpiàn', meaning: 'phim, video' },
                        { char: '旅行', pinyin: 'lǚxíng', meaning: 'du lịch' },
                        { char: '功課', pinyin: 'gōngkè', meaning: 'bài tập' },
                        { char: '出去', pinyin: 'chūqù', meaning: 'đi ra ngoài' },
                        { char: '大概', pinyin: 'dàgài', meaning: 'khoảng' },
                        { char: '放假', pinyin: 'fàngjià', meaning: 'nghỉ lễ' },
                        { char: '多久', pinyin: 'duōjiǔ', meaning: 'bao lâu' },
                        { char: '女', pinyin: 'nǚ', meaning: 'nữ' },
                        { char: '月', pinyin: 'yuè', meaning: 'tháng' },
                        { char: '號', pinyin: 'hào', meaning: 'ngày, số' },
                        { char: '帶', pinyin: 'dài', meaning: 'mang, dắt' },
                        { char: '她', pinyin: 'tā', meaning: 'cô ấy' },
                        { char: '還', pinyin: 'hái', meaning: 'vẫn, còn' },
                        { char: '建議', pinyin: 'jiànyì', meaning: 'gợi ý' },
                        { char: '夜市', pinyin: 'yèshì', meaning: 'chợ đêm' },
                        { char: '應該', pinyin: 'yīnggāi', meaning: 'nên' },
                        { char: '逛', pinyin: 'guàng', meaning: 'đi dạo' },
                        { char: '特別', pinyin: 'tèbié', meaning: 'đặc biệt' },
                        { char: '茶館', pinyin: 'cháguǎn', meaning: 'quán trà' },
                        { char: '決定', pinyin: 'juédìng', meaning: 'quyết định' },
                        { char: '要是', pinyin: 'yàoshi', meaning: 'nếu' },
                        { char: '就', pinyin: 'jiù', meaning: 'thì, liền' },
                    ],
                    grammar: [
                        { title: '...的時候 (de shíhòu)', content: 'Khi... <i>Ví dụ: 放假的時候，你常去旅行嗎？</i>' },
                        { title: '有時候...有時候...', content: 'Có lúc...có lúc... <i>Ví dụ: 有時候在家寫功課，有時候出去玩。</i>' },
                        { title: 'Điều kiện 要是...就... (yàoshi...jiù...)', content: 'Nếu...thì... <i>Ví dụ: 要是那時候我有空，就跟你們一起去。</i>' },
                    ]
                },
                {
                    lesson: 10,
                    title: '臺灣的水果很好吃 (Trái cây Đài Loan rất ngon)',
                    vocab: [
                        { char: '水果', pinyin: 'shuǐguǒ', meaning: 'trái cây' },
                        { char: '黃色', pinyin: 'huángsè', meaning: 'màu vàng' },
                        { char: '芒果', pinyin: 'mángguǒ', meaning: 'xoài' },
                        { char: '給', pinyin: 'gěi', meaning: 'cho' },
                        { char: '塊', pinyin: 'kuài', meaning: 'miếng' },
                        { char: '香', pinyin: 'xiāng', meaning: 'thơm' },
                        { char: '甜', pinyin: 'tián', meaning: 'ngọt' },
                        { char: '紅色', pinyin: 'hóngsè', meaning: 'màu đỏ' },
                        { char: '西瓜', pinyin: 'xīguā', meaning: 'dưa hấu' },
                        { char: '以前', pinyin: 'yǐqián', meaning: 'trước đây' },
                        { char: '機會', pinyin: 'jīhuì', meaning: 'cơ hội' },
                        { char: '請', pinyin: 'qǐng', meaning: 'mời (ăn uống)' },
                        { char: '拍', pinyin: 'pāi', meaning: 'chụp (ảnh)' },
                        { char: '笑', pinyin: 'xiào', meaning: 'cười' },
                        { char: '開心', pinyin: 'kāixīn', meaning: 'vui vẻ' },
                        { char: '穿', pinyin: 'chuān', meaning: 'mặc' },
                        { char: '衣服', pinyin: 'yīfu', meaning: 'quần áo' },
                        { char: '旅館', pinyin: 'lǚguǎn', meaning: 'khách sạn' },
                        { char: '太太', pinyin: 'tàitai', meaning: 'bà, vợ' },
                        { char: '男', pinyin: 'nán', meaning: 'nam' },
                        { char: '矮', pinyin: 'ǎi', meaning: 'lùn, thấp' },
                        { char: '高', pinyin: 'gāo', meaning: 'cao' },
                        { char: '弟弟', pinyin: 'dìdi', meaning: 'em trai' },
                        { char: '乾淨', pinyin: 'gānjìng', meaning: 'sạch sẽ' },
                        { char: '窗戶', pinyin: 'chuānghu', meaning: 'cửa sổ' },
                        { char: '往', pinyin: 'wǎng', meaning: 'hướng về' },
                        { char: '藍色', pinyin: 'lánsè', meaning: 'màu xanh lam' },
                        { char: '因為', pinyin: 'yīnwèi', meaning: 'bởi vì' },
                        { char: '住', pinyin: 'zhù', meaning: 'ở, sống' },
                    ],
                    grammar: [
                        { title: 'VV看 (kàn)', content: 'Làm thử xem. <i>Ví dụ: 吃吃看。(Ăn thử xem).</i>' },
                        { title: 'Lặp lại tính từ', content: 'Nhấn mạnh. <i>Ví dụ: 香香的、甜甜的。</i>' },
                        { title: 'Mệnh đề làm định ngữ', content: 'Mệnh đề + 的 + Danh từ. <i>Ví dụ: 你說的水果是西瓜。</i>' },
                        { title: 'Trợ từ 了 (le) chỉ sự thay đổi', content: '<i>Ví dụ: 我現在很喜歡了。</i>' },
                        { title: '因為...所以... (yīnwèi...suǒyǐ...)', content: 'Bởi vì...cho nên... <i>Ví dụ: 因為旅館不太貴，所以我想去住。</i>' },
                    ]
                },
                {
                    lesson: 11,
                    title: '我要租房子 (Tôi muốn thuê nhà)',
                    vocab: [
                        { char: '租', pinyin: 'zū', meaning: 'thuê' },
                        { char: '房東', pinyin: 'fángdōng', meaning: 'chủ nhà' },
                        { char: '客廳', pinyin: 'kètīng', meaning: 'phòng khách' },
                        { char: '廚房', pinyin: 'chúfáng', meaning: 'nhà bếp' },
                        { char: '左邊/右邊', pinyin: 'zuǒbiān/yòubiān', meaning: 'bên trái/bên phải' },
                        { char: '浴室', pinyin: 'yùshì', meaning: 'phòng tắm' },
                        { char: '超市', pinyin: 'chāoshì', meaning: 'siêu thị' },
                        { char: '走路', pinyin: 'zǒulù', meaning: 'đi bộ' },
                        { char: '間', pinyin: 'jiān', meaning: 'gian (phòng)' },
                        { char: '空', pinyin: 'kōng', meaning: 'trống' },
                        { char: '房間', pinyin: 'fángjiān', meaning: 'căn phòng' },
                        { char: '套房', pinyin: 'tàofáng', meaning: 'phòng khép kín' },
                        { char: '回去', pinyin: 'huíqù', meaning: 'đi về' },
                        { char: '電話', pinyin: 'diànhuà', meaning: 'điện thoại' },
                        { char: '房租', pinyin: 'fángzū', meaning: 'tiền thuê nhà' },
                        { char: '已經', pinyin: 'yǐjīng', meaning: 'đã' },
                        { char: '習慣', pinyin: 'xíguàn', meaning: 'quen' },
                        { char: '問題', pinyin: 'wèntí', meaning: 'vấn đề' },
                        { char: '熱水器', pinyin: 'rèshuǐqì', meaning: 'máy nước nóng' },
                        { char: '好像', pinyin: 'hǎoxiàng', meaning: 'hình như' },
                        { char: '裝', pinyin: 'zhuāng', meaning: 'lắp đặt' },
                        { char: '不過', pinyin: 'búguò', meaning: 'nhưng' },
                        { char: '付', pinyin: 'fù', meaning: 'trả (tiền)' },
                    ],
                    grammar: [
                        { title: '來 + Động từ', content: 'Đến để làm gì. <i>Ví dụ: 我是來看房子。</i>' },
                        { title: '就 (jiù)', content: 'Chỉ sự việc xảy ra nhanh, sớm. <i>Ví dụ: 走路五分鐘就到了。</i>' },
                        { title: 'Chủ ngữ tồn tại với 有 (yǒu)', content: '<i>Ví dụ: 有人住嗎？</i>' },
                        { title: 'Các loại 會 (huì)', content: '會 (sẽ) + V. <i>Ví dụ: 我會去看。(Tôi sẽ đi xem).</i>' },
                    ]
                },
                {
                    lesson: 12,
                    title: '你在臺灣學多久的中文? (Bạn học tiếng Trung ở Đài Loan bao lâu?)',
                    vocab: [
                        { char: '計畫', pinyin: 'jìhuà', meaning: 'kế hoạch' },
                        { char: '年', pinyin: 'nián', meaning: 'năm' },
                        { char: '久', pinyin: 'jiǔ', meaning: 'lâu' },
                        { char: '時間', pinyin: 'shíjiān', meaning: 'thời gian' },
                        { char: '先', pinyin: 'xiān', meaning: 'trước tiên' },
                        { char: '念', pinyin: 'niàn', meaning: 'học, đọc' },
                        { char: '大學', pinyin: 'dàxué', meaning: 'đại học' },
                        { char: '需要', pinyin: 'xūyào', meaning: 'cần' },
                        { char: '花', pinyin: 'huā', meaning: 'tốn, tiêu' },
                        { char: '獎學金', pinyin: 'jiǎngxuéjīn', meaning: 'học bổng' },
                        { char: '成績', pinyin: 'chéngjī', meaning: 'thành tích' },
                        { char: '學費', pinyin: 'xuéfèi', meaning: 'học phí' },
                        { char: '公司', pinyin: 'gōngsī', meaning: 'công ty' },
                        { char: '替', pinyin: 'tì', meaning: 'thay, cho' },
                        { char: '希望', pinyin: 'xīwàng', meaning: 'hy vọng' },
                        { char: '上班', pinyin: 'shàngbān', meaning: 'đi làm' },
                        { char: '念書', pinyin: 'niànshū', meaning: 'học bài' },
                        { char: '累', pinyin: 'lèi', meaning: 'mệt' },
                        { char: '做生意', pinyin: 'zuò shēngyì', meaning: 'kinh doanh' },
                        { char: '找', pinyin: 'zhǎo', meaning: 'tìm kiếm' },
                        { char: '難', pinyin: 'nán', meaning: 'khó' },
                    ],
                    grammar: [
                        { title: '先...再... (xiān...zài...)', content: '...trước, ...sau. <i>Ví dụ: 我先念一年，再念四年大學。</i>' },
                        { title: 'Nhấn mạnh với 是...的 (shì...de)', content: 'Dùng để nhấn mạnh thời gian, địa điểm... <i>Ví dụ: 我的學費是公司替我付的。</i>' },
                        { title: '以後 (yǐhòu)', content: 'Sau này, sau khi. <i>Ví dụ: 回國以後，打算做什麼？</i>' },
                        { title: '好/難 + Động từ', content: 'Dễ/khó làm gì. <i>Ví dụ: 好找 (dễ tìm), 難學 (khó học).</i>' },
                    ]
                },
                {
                    lesson: 13,
                    title: '生日快樂 (Chúc mừng sinh nhật)',
                    vocab: [
                        { char: '生日', pinyin: 'shēngrì', meaning: 'sinh nhật' },
                        { char: '快樂', pinyin: 'kuàilè', meaning: 'vui vẻ' },
                        { char: '回來', pinyin: 'huílái', meaning: 'quay về' },
                        { char: '忘', pinyin: 'wàng', meaning: 'quên' },
                        { char: '記得', pinyin: 'jìde', meaning: 'nhớ' },
                        { char: '當然', pinyin: 'dāngrán', meaning: 'đương nhiên' },
                        { char: '交換', pinyin: 'jiāohuàn', meaning: 'trao đổi' },
                        { char: '熱心', pinyin: 'rèxīn', meaning: 'nhiệt tình' },
                        { char: '一樣', pinyin: 'yíyàng', meaning: 'giống nhau' },
                        { char: '過', pinyin: 'guò', meaning: 'đón, ăn (lễ)' },
                        { char: '左右', pinyin: 'zuǒyòu', meaning: 'khoảng' },
                        { char: '門口', pinyin: 'ménkǒu', meaning: 'cổng, cửa' },
                        { char: '禮物', pinyin: 'lǐwù', meaning: 'quà' },
                        { char: '訂', pinyin: 'dìng', meaning: 'đặt trước' },
                        { char: '了', pinyin: 'le', meaning: 'rồi (trợ từ)' },
                        { char: '豬腳麵線', pinyin: 'zhūjiǎo miànxiàn', meaning: 'mì sợi giò heo' },
                        { char: '蛋', pinyin: 'dàn', meaning: 'trứng' },
                        { char: '傳統', pinyin: 'chuántǒng', meaning: 'truyền thống' },
                        { char: '年輕', pinyin: 'niánqīng', meaning: 'trẻ' },
                        { char: '蛋糕', pinyin: 'dàngāo', meaning: 'bánh ngọt' },
                        { char: '對', pinyin: 'duì', meaning: 'đối với' },
                        { char: '祝', pinyin: 'zhù', meaning: 'chúc' },
                    ],
                    grammar: [
                        { title: '一...就... (yī...jiù...)', content: 'Hễ...là... <i>Ví dụ: 我一下課，就去你學校找你。</i>' },
                        { title: 'Trợ từ động thái 了 (le)', content: 'Đứng sau động từ, chỉ hành động hoàn thành. <i>Ví dụ: 我已經訂了豬腳麵線。</i>' },
                        { title: 'Từ nghi vấn + 都 (dōu)', content: 'Bao hàm toàn bộ. <i>Ví dụ: 我什麼都吃。</i>' },
                        { title: '是不是 (shì bú shì)', content: 'Dùng để xác nhận. <i>Ví dụ: 過生日是不是都吃這些東西？</i>' },
                        { title: 'So sánh với 跟...一樣 (gēn...yíyàng)', content: 'Giống như... <i>Ví dụ: 跟你們一樣，吃蛋糕。</i>' },
                    ]
                },
                {
                    lesson: 14,
                    title: '天氣這麼冷! (Thời tiết lạnh quá!)',
                    vocab: [
                        { char: '天氣', pinyin: 'tiānqì', meaning: 'thời tiết' },
                        { char: '冷', pinyin: 'lěng', meaning: 'lạnh' },
                        { char: '風', pinyin: 'fēng', meaning: 'gió' },
                        { char: '下雪', pinyin: 'xiàxuě', meaning: 'tuyết rơi' },
                        { char: '滑雪', pinyin: 'huáxuě', meaning: 'trượt tuyết' },
                        { char: '春天', pinyin: 'chūntiān', meaning: 'mùa xuân' },
                        { char: '新年', pinyin: 'xīnnián', meaning: 'năm mới' },
                        { char: '父母', pinyin: 'fùmǔ', meaning: 'bố mẹ' },
                        { char: '冬天', pinyin: 'dōngtiān', meaning: 'mùa đông' },
                        { char: '秋天', pinyin: 'qiūtiān', meaning: 'mùa thu' },
                        { char: '紅葉', pinyin: 'hóngyè', meaning: 'lá đỏ' },
                        { char: '只', pinyin: 'zhǐ', meaning: 'chỉ' },
                        { char: '雨', pinyin: 'yǔ', meaning: 'mưa' },
                        { char: '傘', pinyin: 'sǎn', meaning: 'ô, dù' },
                        { char: '颱風', pinyin: 'táifēng', meaning: 'bão' },
                        { char: '夏天', pinyin: 'xiàtiān', meaning: 'mùa hè' },
                        { char: '濕', pinyin: 'shī', meaning: 'ẩm ướt' },
                        { char: '討厭', pinyin: 'tǎoyàn', meaning: 'ghét' },
                        { char: '新聞', pinyin: 'xīnwén', meaning: 'tin tức' },
                        { char: '更', pinyin: 'gèng', meaning: 'càng' },
                        { char: '大家', pinyin: 'dàjiā', meaning: 'mọi người' },
                        { char: '小心', pinyin: 'xiǎoxīn', meaning: 'cẩn thận' },
                        { char: '可怕', pinyin: 'kěpà', meaning: 'đáng sợ' },
                        { char: '停', pinyin: 'tíng', meaning: 'dừng' },
                    ],
                    grammar: [
                        { title: '快...了 (kuài...le)', content: 'Sắp...rồi. <i>Ví dụ: 颱風快要來了。</i>' },
                        { title: 'So sánh với 更 (gèng)', content: 'Càng...hơn. <i>Ví dụ: 這次的颱風會比上次的更大。</i>' },
                        { title: 'So sánh kém hơn với 沒有 (méiyǒu)', content: 'A 没有 B + Adj. <i>Ví dụ: 希望這次的沒有上次的那麼可怕。</i>' },
                        { title: 'Cấu trúc "double 了"', content: 'V + 了 + Time Duration + 了. Chỉ hành động đã kéo dài đến hiện tại. <i>Ví dụ: 我在臺灣住了半年多了。</i>' },
                    ]
                },
                {
                    lesson: 15,
                    title: '我很不舒服 (Tôi không được khỏe)',
                    vocab: [
                        { char: '醫生', pinyin: 'yīshēng', meaning: 'bác sĩ' },
                        { char: '一直', pinyin: 'yìzhí', meaning: 'liên tục' },
                        { char: '流鼻水', pinyin: 'liú bíshuǐ', meaning: 'chảy nước mũi' },
                        { char: '頭', pinyin: 'tóu', meaning: 'đầu' },
                        { char: '痛', pinyin: 'tòng', meaning: 'đau' },
                        { char: '胃口', pinyin: 'wèikǒu', meaning: 'khẩu vị' },
                        { char: '差', pinyin: 'chà', meaning: 'kém' },
                        { char: '喉嚨', pinyin: 'hóulóng', meaning: 'cổ họng' },
                        { char: '發炎', pinyin: 'fāyán', meaning: 'bị viêm' },
                        { char: '生病', pinyin: 'shēngbìng', meaning: 'bị ốm' },
                        { char: '發燒', pinyin: 'fāshāo', meaning: 'sốt' },
                        { char: '感冒', pinyin: 'gǎnmào', meaning: 'cảm cúm' },
                        { char: '藥', pinyin: 'yào', meaning: 'thuốc' },
                        { char: '藥局', pinyin: 'yàojú', meaning: 'hiệu thuốc' },
                        { char: '拿', pinyin: 'ná', meaning: 'lấy, cầm' },
                        { char: '把', pinyin: 'bǎ', meaning: '(câu chữ bǎ)' },
                        { char: '水', pinyin: 'shuǐ', meaning: 'nước' },
                        { char: '休息', pinyin: 'xiūxi', meaning: 'nghỉ ngơi' },
                        { char: '睡覺', pinyin: 'shuìjiào', meaning: 'ngủ' },
                        { char: '臉色', pinyin: 'liǎnsè', meaning: 'sắc mặt' },
                        { char: '肚子', pinyin: 'dùzi', meaning: 'bụng' },
                        { char: '吐', pinyin: 'tù', meaning: 'nôn' },
                        { char: '次', pinyin: 'cì', meaning: 'lần' },
                        { char: '陪', pinyin: 'péi', meaning: 'đi cùng' },
                        { char: '健康保險', pinyin: 'jiànkāng bǎoxiǎn', meaning: 'bảo hiểm y tế' },
                        { char: '油', pinyin: 'yóu', meaning: 'dầu mỡ' },
                        { char: '冰', pinyin: 'bīng', meaning: 'đá, lạnh' },
                        { char: '別', pinyin: 'bié', meaning: 'đừng' },
                        { char: '關心', pinyin: 'guānxīn', meaning: 'quan tâm' },
                    ],
                    grammar: [
                        { title: 'Câu chữ 把 (bǎ)', content: 'S + 把 + O + V + thành phần khác. Nhấn mạnh sự xử lý đối với tân ngữ. <i>Ví dụ: 回去把藥吃了。</i>' },
                        { title: 'V + 了...就...', content: 'Vừa làm xong...thì... <i>Ví dụ: 吃了東西就吐。</i>' },
                        { title: 'So sánh hành động với 得 (de)', content: 'A + V + 得 + 比 + B + Adj. <i>Ví dụ: 我睡得比昨天好。</i>' },
                        { title: 'Bổ ngữ chỉ mức độ', content: '...得多 (nhiều hơn), ...一點 (một chút). <i>Ví dụ: 臉色比早上好得多了。</i>' },
                        { title: 'Động từ ly hợp', content: 'Động từ có thể tách ra. <i>Ví dụ: 見面 -> 見一面 (gặp một lần).</i>' },
                    ]
                }
            ]
        }; 